using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.IO;
using OutLook = Microsoft.Office.Interop.Outlook;
using System.Web;
using System.Net;

namespace OutlookMail
{
    class AutomateJobs : MasterClass
    {

        //****************************************************
        // This class is designed to respond to automated emails
        // generated by other suppliers through a citrix reciever
        // system.
        //****************************************************

        public AutomateJobs()
        {

            //****************************************************
            // Log File Path (For Crash or Error Analysis)
            //****************************************************

            string TriggerPath = @"FolderLocation";

            //****************************************************
            // Itterate through "inbox" sub folders to Find 
            // "CompanyName" Folder
            //****************************************************

            foreach (OutLook.MAPIFolder inbox in myInbox.Folders)
            {
                if (inbox.Name == "CompanyName")
                {
                    CompanyName = inbox;

                    //****************************************************
                    // Itterated through "CompanyName" Sub Folders to find 
                    // "Trigger" Folder
                    //****************************************************

                    foreach (OutLook.MAPIFolder folder2 in CompanyName.Folders)
                    {
                        if (folder2.Name == "Trigger")
                        {
                            Trigger = folder2;

                            //****************************************************
                            // Itterate through "Trigger" Folders email Items
                            //****************************************************

                            OutLook.Items items = Trigger.Items;
                            foreach (OutLook.MailItem mails in items)
                            {
                                Console.WriteLine(mails.Subject);
                                string QuoteNo = sendrequest(mails.Subject);
                                Console.WriteLine("Quote Number:" + QuoteNo);

                                //****************************************************
                                // Write email subject to a log incase of a crash or 
                                // error.
                                //****************************************************

                                File.AppendAllText(TriggerPath, DateTime.Now.ToString() + ": " + mails.Subject + QuoteNo + Environment.NewLine);

                                //****************************************************
                                // Itterate through "Trigger" sub folders to find 
                                // "Processed" Folder then move email to the processed
                                // folder
                                //****************************************************

                                foreach (OutLook.MAPIFolder folder3 in Trigger.Folders)
                                {
                                    if (folder3.Name == "Processed")
                                    {
                                        Processed = folder3;
                                        mails.Move(Processed);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        //****************************************************
        // The sendrequest function checks the company database
        // for any quotes for the recieved automated email. If 
        // we have provided a quote this function will return 
        // the customer client number and company quote number
        // which is currently being used in the log but could
        // be extended out for many other uses.
        //****************************************************

        static string sendrequest(string clientno)
        {
            using (var client = new WebClient())  
            {
                string quoteno = client.DownloadString("CompanyWebsite" + clientno);
                return quoteno;
            }
        }
    }
}
